### ISSUE TITLE
Falta crear Cards

### ISSUE THREAD

**Issue by saulmontesdeoca** [DiegoMA1/equipo-1#11]
## Falta cards
Ejemplos:

![grid1](https://user-images.githubusercontent.com/29721482/96949214-fc9cd880-14ac-11eb-97a9-1916bec1d2b3.jpeg)
![grid2](https://user-images.githubusercontent.com/29721482/96949222-0292b980-14ad-11eb-9d45-b9e15e67e956.jpeg)
![grid3](https://user-images.githubusercontent.com/29721482/96949253-19391080-14ad-11eb-8dc0-583b56795ca1.jpeg)

**Comment by DiegoMA1** [comment]
En master ya esta la primera grafica, si pueden chequenla para hacer las demás con ese componente y cerrar el issue =D
